//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace KitchenPlan
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class KitchenPlanEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new KitchenPlanEntities object using the connection string found in the 'KitchenPlanEntities' section of the application configuration file.
        /// </summary>
        public KitchenPlanEntities() : base("name=KitchenPlanEntities", "KitchenPlanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KitchenPlanEntities object.
        /// </summary>
        public KitchenPlanEntities(string connectionString) : base(connectionString, "KitchenPlanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KitchenPlanEntities object.
        /// </summary>
        public KitchenPlanEntities(EntityConnection connection) : base(connection, "KitchenPlanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PantryItem> PantryItems
        {
            get
            {
                if ((_PantryItems == null))
                {
                    _PantryItems = base.CreateObjectSet<PantryItem>("PantryItems");
                }
                return _PantryItems;
            }
        }
        private ObjectSet<PantryItem> _PantryItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PlannedMeal> PlannedMeals
        {
            get
            {
                if ((_PlannedMeals == null))
                {
                    _PlannedMeals = base.CreateObjectSet<PlannedMeal>("PlannedMeals");
                }
                return _PlannedMeals;
            }
        }
        private ObjectSet<PlannedMeal> _PlannedMeals;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PantryItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPantryItems(PantryItem pantryItem)
        {
            base.AddObject("PantryItems", pantryItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PlannedMeals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlannedMeals(PlannedMeal plannedMeal)
        {
            base.AddObject("PlannedMeals", plannedMeal);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KitchenPlan.Model", Name="PantryItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PantryItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PantryItem object.
        /// </summary>
        /// <param name="pantryItemId">Initial value of the PantryItemId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static PantryItem CreatePantryItem(global::System.Int32 pantryItemId, global::System.String description)
        {
            PantryItem pantryItem = new PantryItem();
            pantryItem.PantryItemId = pantryItemId;
            pantryItem.Description = description;
            return pantryItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PantryItemId
        {
            get
            {
                return _PantryItemId;
            }
            set
            {
                if (_PantryItemId != value)
                {
                    OnPantryItemIdChanging(value);
                    ReportPropertyChanging("PantryItemId");
                    _PantryItemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PantryItemId");
                    OnPantryItemIdChanged();
                }
            }
        }
        private global::System.Int32 _PantryItemId;
        partial void OnPantryItemIdChanging(global::System.Int32 value);
        partial void OnPantryItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KitchenPlan.Model", Name="PlannedMeal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PlannedMeal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PlannedMeal object.
        /// </summary>
        /// <param name="plannedMealID">Initial value of the PlannedMealID property.</param>
        public static PlannedMeal CreatePlannedMeal(global::System.Int32 plannedMealID)
        {
            PlannedMeal plannedMeal = new PlannedMeal();
            plannedMeal.PlannedMealID = plannedMealID;
            return plannedMeal;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlannedMealID
        {
            get
            {
                return _PlannedMealID;
            }
            set
            {
                if (_PlannedMealID != value)
                {
                    OnPlannedMealIDChanging(value);
                    ReportPropertyChanging("PlannedMealID");
                    _PlannedMealID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PlannedMealID");
                    OnPlannedMealIDChanged();
                }
            }
        }
        private global::System.Int32 _PlannedMealID;
        partial void OnPlannedMealIDChanging(global::System.Int32 value);
        partial void OnPlannedMealIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PantryItemID
        {
            get
            {
                return _PantryItemID;
            }
            set
            {
                OnPantryItemIDChanging(value);
                ReportPropertyChanging("PantryItemID");
                _PantryItemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PantryItemID");
                OnPantryItemIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PantryItemID;
        partial void OnPantryItemIDChanging(Nullable<global::System.Int32> value);
        partial void OnPantryItemIDChanged();

        #endregion
    
    }

    #endregion
    
}
